### ISSUE TITLE
Method return changes to true instead of false

### ISSUE THREAD

**Issue by nampud** [Raslin777/XposedAdvancedLogging#2]
Bug is caused by this code in `HackService.java` line 1105

``` java
 } else if (ReturnString.equals("!false")) {
           param.setResult(true); // should be setResult(false)
           XposedBridge.log("We Change Method with bool false");
}
```

I would make a pull request but this is a simple change and it would have to be accepted/merged anyway.

**Comment by Raslin777** [comment]
Ty, 
https://github.com/Raslin777/XposedAdvancedLogging/commit/618259a037eb756d2d31659dbac16610885b904c
