### ISSUE TITLE
Unable to create log file

### ISSUE THREAD

**Issue by daimoniuma** [Raslin777/XposedAdvancedLogging#3]
```
12-12 00:48:29.607 E/Xposed  (2847): java.io.FileNotFoundException: /data/data/org.raslin777.advancedLogging/classes.txt: open failed: ENOENT (No such file or directory)
12-12 00:48:29.607 E/Xposed  (2847): 	at libcore.io.IoBridge.open(IoBridge.java:456)
12-12 00:48:29.607 E/Xposed  (2847): 	at java.io.FileInputStream.<init>(FileInputStream.java:76)
12-12 00:48:29.607 E/Xposed  (2847): 	at java.util.Scanner.<init>(Scanner.java:158)
12-12 00:48:29.607 E/Xposed  (2847): 	at java.util.Scanner.<init>(Scanner.java:138)
12-12 00:48:29.607 E/Xposed  (2847): 	at org.raslin777.advancedLogging.HackService.handleLoadPackage(HackService.java:812)
12-12 00:48:29.607 E/Xposed  (2847): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
12-12 00:48:29.607 E/Xposed  (2847): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
12-12 00:48:29.607 E/Xposed  (2847): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
12-12 00:48:29.607 E/Xposed  (2847): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:116)
12-12 00:48:29.607 E/Xposed  (2847): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:314)
12-12 00:48:29.607 E/Xposed  (2847): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
12-12 00:48:29.607 E/Xposed  (2847): 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
12-12 00:48:29.607 E/Xposed  (2847): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1370)
12-12 00:48:29.607 E/Xposed  (2847): 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-12 00:48:29.607 E/Xposed  (2847): 	at android.os.Looper.loop(Looper.java:135)
12-12 00:48:29.607 E/Xposed  (2847): 	at android.app.ActivityThread.main(ActivityThread.java:5356)
12-12 00:48:29.607 E/Xposed  (2847): 	at java.lang.reflect.Method.invoke(Native Method)
12-12 00:48:29.607 E/Xposed  (2847): 	at java.lang.reflect.Method.invoke(Method.java:372)
12-12 00:48:29.607 E/Xposed  (2847): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
12-12 00:48:29.607 E/Xposed  (2847): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
12-12 00:48:29.607 E/Xposed  (2847): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
12-12 00:48:29.607 E/Xposed  (2847): Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
12-12 00:48:29.607 E/Xposed  (2847): 	at libcore.io.Posix.open(Native Method)
12-12 00:48:29.607 E/Xposed  (2847): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
12-12 00:48:29.607 E/Xposed  (2847): 	at libcore.io.IoBridge.open(IoBridge.java:442)
12-12 00:48:29.607 E/Xposed  (2847): 	... 20 more
```

**Comment by Raslin777** [comment]
/data/data/org.raslin777.advancedLogging/classes.txt

Is not a log file. It logs to logcat. classes.text is where you put the classes you want to hook.

**Comment by daimoniuma** [comment]
I told you about methods hook. I can't find any log in .../Android/data/... Both internal & external SD.

**Comment by Raslin777** [comment]
Can you please upload you classes.txt

This is required to hook methods. If you don't know the classes to put into classes.txt you can use the dump all classes function.

**Comment by daimoniuma** [comment]
Ups, sorry. I thought that function "Hook all methods in classes" should log all executed methods in the whole app. Now I realized that it isn't.

I'll try to put needed classes to classes.txt and see if it will work.

Sorry, but you did too twisted scheme. Classes are saved in /data/data/monitored.app/myfile.txt. Methods you hook from /data/data/advanced.logging/classes.txt...

Could you get all your stuff from one directory specified by user (/external_SD/logs, for example). It will be more comfortable to have it in one place. And create txt with "package_name" instead of "myfile"...

One more solution: create empty classes.txt if it isn't exist. It will help to avoid described error and will be more comfortable for user to have empty file and not create it by my own.

Also I think it would be better to provide ability to add needed classes within Adv Log interface (optional).

Thanks.

**Comment by daimoniuma** [comment]
Lol, topic is defined correctly anyway, because you output all stuff to logcat. Could you make output to .txt?

**Comment by Artieza** [comment]
Also I think it would be better to provide ability to add needed classes within Adv Log interface (optional).

**Comment by Raslin777** [comment]
Yes, I could output to a log file. Yes it could do a check if file exists and create it if it is not. No I cannot change the output and read/write locations of the classes.txt and the myfile.txt, its a permission issue when in the hook(HookedApp) and outside(MyApp) of the hook, I'm sure a more elegant approach could be crafted but I have extremely limited time.  When I get more time I will consider changing some of your requests. Ty for the information and feedback.
